### ISSUE TITLE
`.mm-convert__value` padding issue on desktop

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/sample-currency-converter#2]
Not sure where to override the behavior of `.mm-convert__value` but currently it's wrong to use padding. Instead with margin the issue is fixed.

Before:
![screen shot 2017-04-22 at 14 49 36-fullpage](https://cloud.githubusercontent.com/assets/349621/25304208/48e823da-276b-11e7-9609-d56bfe855b4a.png)

After:
![screen shot 2017-04-22 at 14 49 52-fullpage](https://cloud.githubusercontent.com/assets/349621/25304209/4f1ea88c-276b-11e7-8e2c-1b0cf638eb97.png)

I could make a PR if someone gave me a hint where to place the override.

**Comment by sgomes** [comment]
Thanks for filing this issue, @XhmikosR!

I'm having trouble reproducing the visual glitch in your "before" image. Could you provide some more details on your browser and system?

**Comment by XhmikosR** [comment]
Sorry for the lack of info, I assumed the issue happens with most browsers.

I'm using Firefox 54.0 beta1 on Windows 10 64-bit.

**Comment by sgomes** [comment]
Thanks, @XhmikosR! I see the same issue in Firefox 54.0 beta1 on macOS 10.12.04. I'll take a look and see if I can figure out what's going on.

**Comment by XhmikosR** [comment]
It's due to padding, see my OP. Switching to margin for `.mm-convert__value` fixes the issue. I'm just not sure in which file to place this otherwise I'd make a PR.

**Comment by sgomes** [comment]
@XhmikosR: Ah yes, got it. `margin` seems to do the trick, yes, and it's likely a better approach than `padding`, as you point out. Something must have changed in Firefox recently, as 53.0 doesn't show this issue.

If you'd like to make the change yourself, this is the right spot: https://github.com/GoogleChrome/sample-currency-converter/blob/master/styles/critical/convert.css#L158

Thanks again!

**Comment by XhmikosR** [comment]
Ah, I saw that but I was under the impression those css files were auto generated. I'll make the change and submit a PR.
